AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instance with Docker and Nginx website

Parameters:
  KeyName:
    Type: String
    Description: EC2 Key Pair name for SSH access

Resources:
  MyInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316  # Amazon Linux 2 AMI in most regions
      SecurityGroupIds:
        - !Ref MyInstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install docker -y
          service docker start
          usermod -a -G docker ec2-user
          docker run -d -p 80:80 ghcr.io/YOUR_GITHUB_ORG/YOUR_REPO:latest

Outputs:
  WebsiteURL:
    Value: !Sub "http://${MyEC2Instance.PublicIp}"
    Description: Public URL of the website
