name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=sujan-div_aws-docker-site
            -Dsonar.organization=sujan-div
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.branch.name=main

      - name: Build Docker Image
        run: |
          docker build -t my-website .
          
      - name: Tag and Push Docker Image to GHCR
        run: |
          # Use your personal namespace, not org, unless you’ve fixed org permissions
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/aws-docker-site
          
          docker tag my-website $IMAGE_NAME
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push $IMAGE_NAME

      - name: Trigger CloudFormation (placeholder)
        run: echo "Manual deployment or use AWS CLI"
