# .github/workflows/pipeline.yaml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Sujan-div_aws-docker-site
            -Dsonar.organization=sujan-div
            -Dsonar.host.url=https://sonarcloud.io

      - name: Build Docker Image
        run: |
          docker build -t my-website .
          docker tag my-website ghcr.io/Sujan-div/aws-docker-site:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u USERNAME --password-stdin
          docker push ghcr.io/Sujan-div/aws-docker-site:latest

      - name: Trigger CloudFormation (optional – requires AWS credentials)
        run: echo "Manual deployment or use AWS CLI"
